# Generated by Django 3.1.7 on 2021-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuserprofile',
            name='DoB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customeuserprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
