# Generated by Django 3.1.7 on 2021-04-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0003_auto_20210405_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
