# Generated by Django 3.1.7 on 2021-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
