# Generated by Django 3.1.7 on 2021-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0006_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='groupName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
