# Generated by Django 3.1.7 on 2021-04-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0012_auto_20210420_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuserprofile',
            name='DoB',
        ),
    ]
