# Generated by Django 3.1.7 on 2021-04-21 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0013_remove_customeuserprofile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='cu_pro',
        ),
        migrations.AddField(
            model_name='chatclients',
            name='cu_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
    ]
