# Generated by Django 3.1.7 on 2021-04-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0014_auto_20210421_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatclients',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='chatclients',
            name='cu_pro',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='groupName',
        ),
        migrations.AddField(
            model_name='chatclients',
            name='groupName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='cu_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='shabd.chatclients'),
        ),
        migrations.AddField(
            model_name='customeuserprofile',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_name', to='shabd.chatclients'),
        ),
    ]
