# Generated by Django 3.1.7 on 2021-04-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0015_auto_20210421_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatclients',
            name='groupName',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='cu_pro',
        ),
        migrations.RemoveField(
            model_name='customeuserprofile',
            name='channel',
        ),
        migrations.AddField(
            model_name='chatclients',
            name='channel_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='channel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chanl_id', to='shabd.chatclients'),
        ),
    ]
