# Generated by Django 3.1.7 on 2021-05-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0017_chatclients_cu_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatclients',
            name='cu_pro',
        ),
        migrations.AddField(
            model_name='chatclients',
            name='name',
            field=models.CharField(default='aaa', max_length=100),
        ),
    ]
