# Generated by Django 3.1.7 on 2021-05-13 07:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0019_chatnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatNotification',
            new_name='ChatNotificationModel',
        ),
        migrations.AlterModelManagers(
            name='chatnotificationmodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
