# Generated by Django 3.1.7 on 2021-06-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0020_auto_20210513_0739'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatnotificationmodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customeuserprofile',
            name='userImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
