# Generated by Django 3.1.7 on 2021-06-12 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0022_auto_20210612_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='userImage',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
