# Generated by Django 3.1.7 on 2021-06-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0024_auto_20210612_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='channel_id',
        ),
        migrations.DeleteModel(
            name='ChatClients',
        ),
    ]
