# Generated by Django 3.1.7 on 2021-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0027_remove_chatmessage_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
