# Generated by Django 3.1.7 on 2021-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0029_auto_20210616_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotificationmodel',
            name='sender',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
