# Generated by Django 3.2.4 on 2021-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0030_auto_20210619_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnotificationmodel',
            name='sender',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
