# Generated by Django 3.2.4 on 2021-06-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0031_alter_chatnotificationmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
