# Generated by Django 3.2.4 on 2021-06-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0033_auto_20210627_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendslist',
            name='username',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
