# Generated by Django 3.2.4 on 2021-07-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0037_alter_friendslist_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='username',
        ),
        migrations.AddField(
            model_name='friendslist',
            name='usernm',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='friends',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
