# Generated by Django 3.2.4 on 2021-07-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0039_auto_20210704_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='usernm',
            field=models.CharField(max_length=350),
        ),
    ]
