# Generated by Django 3.2.4 on 2021-07-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0040_alter_friendslist_usernm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuserprofile',
            name='userImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
