# Generated by Django 3.2.4 on 2021-07-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0041_alter_customeuserprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuserprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
