# Generated by Django 3.2.4 on 2021-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0042_alter_customeuserprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuserprofile',
            name='userImage',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
