# Generated by Django 3.2.4 on 2021-07-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0043_alter_customeuserprofile_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatClients',
        ),
    ]
