# Generated by Django 3.2.4 on 2021-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0044_delete_chatclients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuserprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='customeuserprofile',
            name='DoB',
            field=models.DateField(null=True),
        ),
    ]
