# Generated by Django 3.2.4 on 2021-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0046_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
