# Generated by Django 3.2.4 on 2021-08-05 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0047_chatgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='groupName',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
