# Generated by Django 3.2.4 on 2021-08-05 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0048_alter_groupmessage_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='groupname should be minimun three charachter long')]),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='groupName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
