# Generated by Django 3.2.4 on 2021-08-08 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0049_auto_20210806_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupname',
            field=models.CharField(blank=True, max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='groupname should be minimun three charachter long'), django.core.validators.RegexValidator('^[\\w]+$')]),
        ),
    ]
