# Generated by Django 3.2.4 on 2022-04-16 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0050_alter_chatgroup_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
