# Generated by Django 3.2.4 on 2022-09-04 13:14

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0051_alter_friendslist_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupImage', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='groupImage',
            field=models.ImageField(blank=True, storage=storages.backends.dropbox.DropBoxStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shabd.groupimages'),
        ),
    ]
